name: API Deployment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  build-push-image-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::010928227743:role/githubactions-role
          aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Configure Python environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Model download
      run: python -m model_downloader  

    - name: Unit testing
      run: pytest

    - name: Linting
      run: pylint src

    # --- habilita build arm64 no runner amd64 ---
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build ARM64 e push direto para o ECR
    - name: Build and Push (arm64) to ECR
      run: |
        docker buildx build \
          --platform linux/arm64 \
          -t 010928227743.dkr.ecr.us-east-1.amazonaws.com/quantum-finance/credit-score:latest \
          --push \
          .

    - name: Update Lambda (image)
      run: |
        aws lambda update-function-code \
          --function-name score-credit-api \
          --image-uri 010928227743.dkr.ecr.us-east-1.amazonaws.com/quantum-finance/credit-score:latest \
          --region us-east-1