name: Pull Request Review

on:

  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
    pull-request-review:
        runs-on: ubuntu-latest

        permissions:
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Configure Python environment
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"           
                
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::010928227743:role/githubactions-role
                aws-region: us-east-1
            
            - name: Install dependencies
              run: python -m pip install -r requirements.txt

            - name: Model download
              run: python -m model_downloader.py

            - name: Unit testing
              run: pytest

            - name: Linting
              run: pylint src
            
            - name: Build image
              run: docker build --platform linux/arm64 -t quantum-finance/credit-score .